name: build-publish-site
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: .github/build-publish-site
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
