name: build-publish-site
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: yarn build
      - run: yarn publish-site
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
